### ISSUE TITLE
建议 SMTP 不需要 TLS 或身份验证也能运行

### ISSUE THREAD

**Issue by shenleg** [Aqr-K/MoviePilot-Plugins-PR#1]
我本地配置的 SMTP 服务器不需要身份验证，但是程序必须参数填完整才能运行
 -> 【WARNING】2024-04-06 14:27:44,196 - smtpmsg - 参数配置不完整，关闭插件

建议身份验证也是一个可选项

**Comment by Aqr-K** [comment]
v2.0问题还存在吗？
如果还是这样，打开MP的debug模式，把日志完整版发上来看看？我看看大概是哪一部分出问题了，身份验证目前应该是不作为插件状态的识别的

**Comment by Aqr-K** [comment]
好像不用了，定位到问题了

**Comment by Aqr-K** [comment]
问题已做修复，更新v2.1版本试试
